"""Execution Receipts — signed proof of stage completion.

Each pipeline stage that completes successfully generates an ``ExecutionReceipt``:
an HMAC-SHA256-signed record that binds:
  - the turn ID
  - the stage name
  - the deterministic ``stage_call_id`` (from ExecutionRecovery)
  - the checkpoint hash after the stage
  - a monotonic sequence counter

Receipts are chained: each receipt includes the signature of the previous one.
This creates a tamper-evident continuity chain across the lifetime of a turn —
including across crash boundaries.

On resume, ``ReceiptChain.verify_continuity()`` confirms:
  1. Every receipt signature is valid.
  2. The chain is unbroken (no gaps in sequence numbers).
  3. The expected stages are present.
  4. No new receipts exist with earlier timestamps than existing ones.

Why receipts are now *critical* (not just nice-to-have)
---------------------------------------------------------
Because execution may span multiple process lifetimes (crash → resume), there
is no single in-memory witness for the full execution.  Receipts are the
persistent proof that a particular stage ran, completed, and produced a
specific checkpoint hash.  Without them, an adversary (or a bug) could resume
into a state that skips a critical stage without detection.

Architecture role
-----------------
Receipts are generated by TurnGraph after each stage and stored in:
  a. ``TurnContext.state["_execution_receipts"]``  (in-memory, for the current run)
  b. Optionally persisted by the caller (e.g. alongside the resume record)

The receipts are NOT stored in TurnResumeStore by default — that keeps the
store minimal.  Callers who want fully durable receipts should call
``ReceiptChain.to_dict()`` and write it alongside the resume record.
"""
from __future__ import annotations

import hashlib
import hmac
import json
import os
import time
from dataclasses import dataclass, field
from typing import Any, Sequence


# ---------------------------------------------------------------------------
# Receipt
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ExecutionReceipt:
    """Signed proof that a pipeline stage completed successfully.

    Attributes
    ----------
    turn_id:
        The ``trace_id`` of the turn this receipt belongs to.
    stage:
        Name of the pipeline stage (e.g. ``"temporal"``, ``"inference"``).
    sequence:
        Monotonically increasing counter across the full turn (including
        across crash boundaries).
    stage_call_id:
        Deterministic idempotency key ``sha256(turn_id:stage)[:32]``.
    checkpoint_hash:
        The ``TurnContext.last_checkpoint_hash`` after the stage completed.
    prev_receipt_sig:
        Signature of the immediately preceding receipt in the chain (empty
        string for the very first receipt).
    completed_at:
        Wall-clock epoch when the stage completed (advisory; not used in sig).
    signature:
        HMAC-SHA256 of the canonical payload (see ``_signing_payload``).
    """

    turn_id: str
    stage: str
    sequence: int
    stage_call_id: str
    checkpoint_hash: str
    prev_receipt_sig: str
    completed_at: float
    signature: str = ""

    def _signing_payload(self) -> bytes:
        """Deterministic bytes over which the HMAC is computed."""
        payload = json.dumps(
            {
                "turn_id": self.turn_id,
                "stage": self.stage,
                "sequence": self.sequence,
                "stage_call_id": self.stage_call_id,
                "checkpoint_hash": self.checkpoint_hash,
                "prev_receipt_sig": self.prev_receipt_sig,
            },
            sort_keys=True,
        )
        return payload.encode("utf-8")

    def is_valid(self, key: bytes) -> bool:
        """Return True if *signature* is correct for *key*."""
        if not self.signature:
            return False
        expected = hmac.new(key, self._signing_payload(), "sha256").hexdigest()
        return hmac.compare_digest(expected, self.signature)

    def to_dict(self) -> dict[str, Any]:
        return {
            "turn_id": self.turn_id,
            "stage": self.stage,
            "sequence": self.sequence,
            "stage_call_id": self.stage_call_id,
            "checkpoint_hash": self.checkpoint_hash,
            "prev_receipt_sig": self.prev_receipt_sig,
            "completed_at": self.completed_at,
            "signature": self.signature,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "ExecutionReceipt":
        return cls(
            turn_id=str(d.get("turn_id") or ""),
            stage=str(d.get("stage") or ""),
            sequence=int(d.get("sequence") or 0),
            stage_call_id=str(d.get("stage_call_id") or ""),
            checkpoint_hash=str(d.get("checkpoint_hash") or ""),
            prev_receipt_sig=str(d.get("prev_receipt_sig") or ""),
            completed_at=float(d.get("completed_at") or 0.0),
            signature=str(d.get("signature") or ""),
        )


# ---------------------------------------------------------------------------
# Receipt signer
# ---------------------------------------------------------------------------

class ReceiptSigner:
    """Issues and verifies ExecutionReceipt signatures.

    A random 32-byte key is generated per process by default.  For cross-process
    receipt verification (e.g. distributed deployment), provide a stable key via
    the ``secret_key`` parameter or the ``DADBOT_RECEIPT_KEY`` environment variable.
    """

    _ENV_VAR = "DADBOT_RECEIPT_KEY"

    def __init__(self, secret_key: bytes | None = None) -> None:
        env_key = os.environ.get(self._ENV_VAR, "")
        if secret_key:
            self._key = secret_key
        elif env_key:
            self._key = env_key.encode("utf-8")[:64].ljust(32, b"\x00")
        else:
            self._key = os.urandom(32)

    def sign(
        self,
        *,
        turn_id: str,
        stage: str,
        sequence: int,
        stage_call_id: str,
        checkpoint_hash: str,
        prev_receipt_sig: str,
        completed_at: float | None = None,
    ) -> ExecutionReceipt:
        """Create and sign a new ExecutionReceipt."""
        unsigned = ExecutionReceipt(
            turn_id=turn_id,
            stage=stage,
            sequence=sequence,
            stage_call_id=stage_call_id,
            checkpoint_hash=checkpoint_hash,
            prev_receipt_sig=prev_receipt_sig,
            completed_at=completed_at or time.time(),
            signature="",
        )
        sig = hmac.new(self._key, unsigned._signing_payload(), "sha256").hexdigest()
        return ExecutionReceipt(
            turn_id=unsigned.turn_id,
            stage=unsigned.stage,
            sequence=unsigned.sequence,
            stage_call_id=unsigned.stage_call_id,
            checkpoint_hash=unsigned.checkpoint_hash,
            prev_receipt_sig=unsigned.prev_receipt_sig,
            completed_at=unsigned.completed_at,
            signature=sig,
        )

    def verify(self, receipt: ExecutionReceipt) -> bool:
        """Return True if *receipt* has a valid signature for this signer's key."""
        return receipt.is_valid(self._key)


# ---------------------------------------------------------------------------
# Receipt chain
# ---------------------------------------------------------------------------

@dataclass
class ContinuityViolation:
    """Describes a specific continuity problem detected by ReceiptChain.verify_continuity."""
    receipt_index: int
    stage: str
    reason: str


class ReceiptChain:
    """Ordered sequence of ExecutionReceipts for a single turn.

    Stored in ``TurnContext.state["_execution_receipts"]`` as a list of dicts
    (for JSON serialisability).  The chain spans the full turn lifetime,
    including across crash-resume boundaries.

    Usage (from TurnGraph, after each stage)::

        chain = ReceiptChain.from_state(turn_context.state)
        chain.append(signer.sign(
            turn_id=..., stage=..., sequence=chain.next_sequence,
            stage_call_id=..., checkpoint_hash=...,
            prev_receipt_sig=chain.last_signature,
        ))
        chain.write_to_state(turn_context.state)
    """

    _STATE_KEY = "_execution_receipts"

    def __init__(self, receipts: list[ExecutionReceipt] | None = None) -> None:
        self._receipts: list[ExecutionReceipt] = list(receipts or [])

    # ------------------------------------------------------------------
    # Accessors
    # ------------------------------------------------------------------

    @property
    def receipts(self) -> list[ExecutionReceipt]:
        return list(self._receipts)

    @property
    def last_signature(self) -> str:
        """Signature of the last receipt, or empty string if chain is empty."""
        return self._receipts[-1].signature if self._receipts else ""

    @property
    def next_sequence(self) -> int:
        """Sequence number to use for the next receipt."""
        return self._receipts[-1].sequence + 1 if self._receipts else 1

    def __len__(self) -> int:
        return len(self._receipts)

    # ------------------------------------------------------------------
    # Mutation
    # ------------------------------------------------------------------

    def append(self, receipt: ExecutionReceipt) -> None:
        """Add a receipt to the chain."""
        self._receipts.append(receipt)

    # ------------------------------------------------------------------
    # Serialisation
    # ------------------------------------------------------------------

    def to_list(self) -> list[dict[str, Any]]:
        return [r.to_dict() for r in self._receipts]

    @classmethod
    def from_list(cls, lst: list[dict[str, Any]]) -> "ReceiptChain":
        return cls([ExecutionReceipt.from_dict(d) for d in lst])

    @classmethod
    def from_state(cls, state: dict[str, Any]) -> "ReceiptChain":
        """Load chain from TurnContext.state (returns empty chain if absent)."""
        raw = state.get(cls._STATE_KEY)
        if isinstance(raw, list):
            return cls.from_list(raw)
        return cls()

    def write_to_state(self, state: dict[str, Any]) -> None:
        """Persist chain back into TurnContext.state."""
        state[self._STATE_KEY] = self.to_list()

    # ------------------------------------------------------------------
    # Verification
    # ------------------------------------------------------------------

    def verify_continuity(
        self,
        signer: ReceiptSigner,
        *,
        expected_stages: Sequence[str] | None = None,
    ) -> list[ContinuityViolation]:
        """Verify the integrity of the receipt chain.

        Checks:
        1. Every receipt signature is valid.
        2. Sequence numbers are strictly increasing starting from 1.
        3. Each receipt's ``prev_receipt_sig`` matches the previous receipt's sig.
        4. All ``expected_stages`` are present in order (if provided).

        Returns
        -------
        list[ContinuityViolation]
            Empty list if the chain is intact.  Non-empty if violations exist.
        """
        violations: list[ContinuityViolation] = []
        prev_sig = ""
        expected_seq = 1

        for i, receipt in enumerate(self._receipts):
            # Check signature.
            if not signer.verify(receipt):
                violations.append(ContinuityViolation(
                    receipt_index=i,
                    stage=receipt.stage,
                    reason=f"Invalid signature for stage {receipt.stage!r} (sequence {receipt.sequence})",
                ))

            # Check sequence continuity.
            if receipt.sequence != expected_seq:
                violations.append(ContinuityViolation(
                    receipt_index=i,
                    stage=receipt.stage,
                    reason=(
                        f"Sequence gap: expected {expected_seq}, got {receipt.sequence} "
                        f"for stage {receipt.stage!r}"
                    ),
                ))
            expected_seq = receipt.sequence + 1

            # Check prev_receipt_sig linkage.
            if receipt.prev_receipt_sig != prev_sig:
                violations.append(ContinuityViolation(
                    receipt_index=i,
                    stage=receipt.stage,
                    reason=(
                        f"Chain broken at stage {receipt.stage!r}: "
                        f"prev_receipt_sig mismatch"
                    ),
                ))
            prev_sig = receipt.signature

        # Check expected stages present.
        if expected_stages:
            completed = {r.stage for r in self._receipts}
            for stage in expected_stages:
                if stage not in completed:
                    violations.append(ContinuityViolation(
                        receipt_index=-1,
                        stage=stage,
                        reason=f"Expected stage {stage!r} missing from receipt chain",
                    ))

        return violations

    def is_intact(self, signer: ReceiptSigner) -> bool:
        """Return True if verify_continuity() finds no violations."""
        return len(self.verify_continuity(signer)) == 0


# ---------------------------------------------------------------------------
# Module-level default signer (process-scoped; one per process lifetime)
# ---------------------------------------------------------------------------

#: Default signer. Uses DADBOT_RECEIPT_KEY env var if set, else random key.
DEFAULT_SIGNER: ReceiptSigner = ReceiptSigner()
