"""PlannerIR — Immutable Intermediate Representation for Planner output.

Provides typed, immutable dataclasses for planner phase decisions. This IR layer
decouples the planner output from direct turn orchestration and enables:
- Type-safe candidate handling
- Deterministic intent/strategy routing
- Testable planner-to-policy flow
- Boundary isolation between planner and orchestrator

Core IR types:
- CandidateIR: Single candidate with intent/strategy metadata
- PlannerDecision: Complete planner output (candidates, metadata, hints)
- build_planner_ir(): Boundary adapter from PlanResult → PlannerDecision
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class CandidateIR:
    """Immutable representation of a single candidate from planner."""

    candidate_id: str
    candidate: Any  # Opaque candidate object from planner/runtime

    # Intent metadata from execution result
    intent_type: str = ""
    strategy: str = ""

    # Candidate-specific metadata
    metadata: dict[str, Any] = field(default_factory=dict)

    # Opaque runtime reference for compatibility with existing handlers
    _runtime_context: Any = field(default=None, repr=False)


@dataclass(frozen=True)
class PlannerDecision:
    """Immutable planner phase outcome."""

    # List of candidates generated by planner
    candidates: tuple[CandidateIR, ...] = field(default_factory=tuple)

    # Primary intent type from execution phase
    primary_intent: str = ""

    # Primary strategy from execution phase
    primary_strategy: str = ""

    # Metadata from planner (substrate mode, enable flags, etc.)
    metadata: dict[str, Any] = field(default_factory=dict)

    # Evaluation hints from planner (rewards, bias, etc.)
    evaluation_hint: dict[str, Any] = field(default_factory=dict)

    # Opaque runtime reference for backward compatibility
    _runtime_context: Any = field(default=None, repr=False)

    def get_primary_candidate(self) -> CandidateIR | None:
        """Return first candidate or None."""
        return self.candidates[0] if self.candidates else None

    def select_candidate_by_id(self, candidate_id: str) -> CandidateIR | None:
        """Find candidate by ID."""
        for cand in self.candidates:
            if cand.candidate_id == candidate_id:
                return cand
        return None


def build_planner_ir(
    plan_result: Any,
    turn_context: Any,
) -> PlannerDecision:
    """Boundary adapter: PlanResult (runtime) → PlannerDecision (IR).

    Converts untyped planner output into immutable IR representation.
    Preserves opaque runtime_context for handlers that need raw turn_context.

    Args:
        plan_result: PlanResult from planner.build() with candidates, metadata, evaluation_hint
        turn_context: Raw turn context for opaque _runtime_context carrier

    Returns:
        PlannerDecision: Immutable IR representation
    """
    if plan_result is None:
        return PlannerDecision(_runtime_context=turn_context)

    # Extract candidates list (default empty)
    raw_candidates = list(plan_result.candidates or []) if hasattr(plan_result, "candidates") else []
    candidates_ir = tuple(
        CandidateIR(
            candidate_id=_extract_candidate_id(raw_cand, idx),
            candidate=raw_cand,
            intent_type=_extract_candidate_intent(raw_cand),
            strategy=_extract_candidate_strategy(raw_cand),
            metadata=_extract_candidate_metadata(raw_cand),
            _runtime_context=turn_context,
        )
        for idx, raw_cand in enumerate(raw_candidates)
    )

    # Extract metadata and hints
    metadata = dict(plan_result.metadata or {}) if hasattr(plan_result, "metadata") else {}
    evaluation_hint = dict(plan_result.evaluation_hint or {}) if hasattr(plan_result, "evaluation_hint") else {}

    # Extract primary intent/strategy from turn_context execution result
    primary_intent = _extract_primary_intent(turn_context, metadata)
    primary_strategy = _extract_primary_strategy(turn_context, metadata)

    return PlannerDecision(
        candidates=candidates_ir,
        primary_intent=primary_intent,
        primary_strategy=primary_strategy,
        metadata=metadata,
        evaluation_hint=evaluation_hint,
        _runtime_context=turn_context,
    )


# ============================================================================
# Internal extraction helpers (opaque candidate unpacking)
# ============================================================================


def _extract_candidate_id(candidate: Any, index: int) -> str:
    """Extract or generate candidate ID."""
    if candidate is None:
        return f"candidate_{index}"

    # Try common ID field names for dict
    if isinstance(candidate, dict):
        for key in ("candidate_id", "id", "cid"):
            if key in candidate:
                candidate_id = candidate[key]
                if candidate_id:
                    return str(candidate_id)

    # Try common ID field names for objects
    for field_name in ("candidate_id", "id", "cid"):
        if hasattr(candidate, field_name):
            candidate_id = getattr(candidate, field_name, None)
            if candidate_id:
                return str(candidate_id)

    # Fallback to index-based ID
    return f"candidate_{index}"


def _extract_candidate_intent(candidate: Any) -> str:
    """Extract intent_type from candidate."""
    if candidate is None:
        return ""

    for field_name in ("intent_type", "intent", "execution_intent"):
        if hasattr(candidate, field_name):
            val = getattr(candidate, field_name, None)
            if val:
                return str(val)

    if isinstance(candidate, dict):
        for key in ("intent_type", "intent", "execution_intent"):
            if key in candidate:
                return str(candidate[key] or "")

    return ""


def _extract_candidate_strategy(candidate: Any) -> str:
    """Extract strategy from candidate."""
    if candidate is None:
        return ""

    for field_name in ("strategy", "execution_strategy", "plan_strategy"):
        if hasattr(candidate, field_name):
            val = getattr(candidate, field_name, None)
            if val:
                return str(val)

    if isinstance(candidate, dict):
        for key in ("strategy", "execution_strategy", "plan_strategy"):
            if key in candidate:
                return str(candidate[key] or "")

    return ""


def _extract_candidate_metadata(candidate: Any) -> dict[str, Any]:
    """Extract metadata dict from candidate."""
    if candidate is None:
        return {}

    if isinstance(candidate, dict):
        # Return copy of candidate dict minus private fields
        return {k: v for k, v in candidate.items() if not k.startswith("_")}

    # Try common metadata field names
    for field_name in ("metadata", "meta", "props", "attrs"):
        if hasattr(candidate, field_name):
            meta = getattr(candidate, field_name, None)
            if isinstance(meta, dict):
                return dict(meta)

    return {}


def _extract_primary_intent(turn_context: Any, metadata: dict[str, Any]) -> str:
    """Extract primary intent from execution result or metadata."""
    if turn_context is None:
        return metadata.get("intent_type", "")

    # Try extracting from turn_context.execution_result or similar
    execution_result = getattr(turn_context, "execution_result", None) or {}
    initial_result = execution_result.get("initial_result", {})

    for field in ("intent_type", "intent", "execution_intent"):
        if field in initial_result:
            return str(initial_result[field] or "")

    # Fallback to metadata
    return metadata.get("intent_type", "")


def _extract_primary_strategy(turn_context: Any, metadata: dict[str, Any]) -> str:
    """Extract primary strategy from execution result or metadata."""
    if turn_context is None:
        return metadata.get("strategy", "")

    # Try extracting from turn_context.execution_result
    execution_result = getattr(turn_context, "execution_result", None) or {}
    initial_result = execution_result.get("initial_result", {})

    for field in ("strategy", "execution_strategy", "plan_strategy"):
        if field in initial_result:
            return str(initial_result[field] or "")

    # Fallback to metadata
    return metadata.get("strategy", "")
